version: '3.2'

services:
  web:
    image: wugge/battery-price-monitor-frontend:latest
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wugge-frontend.rule=Host(`bpm.wug.ge`)"
      - "traefik.http.services.wugge-frontend.loadbalancer.server.port=3000"
  api:
    image: wugge/battery-price-monitor-api:latest
    container_name: wugge-api
    restart: "unless-stopped"
    expose:
      - 3001
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EXPRESS_PORT: 3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wugge-api.rule=Host(`bpm.wug.ge`) && PathPrefix(`/api`)"
      - "traefik.http.services.wugge-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.wugge-api.middlewares=wugge-api"
      - "traefik.http.middlewares.wugge-api.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.wugge-api.replacepathregex.replacement=/$$1"
  bpm-db:
    image: mariadb:latest
    ports:
      - ${PUBLIC_DB_PORT:-3886}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bpm_db_volume:/var/lib/mysql


volumes:
  bpm_db_volume:

networks:
  default:
    external:
      name:
        traefik_default
